### ISSUE TITLE
Android client stuck on Waiting on initial GNSS fix...

### ISSUE THREAD

**Issue by RuralYak** [bilde2910/Hauk#11]
Android client stuck on Waiting on initial GNSS fix... 

Android 9.0
MIUI Global 10.3.3.0(PEDMIXM)
Model: MI MAX 3

![Screenshot_2019-09-04-19-07-00-637_info varden hauk](https://user-images.githubusercontent.com/25221496/64306522-ef8af600-cf47-11e9-975c-a5366072bfc1.png)

**Comment by bilde2910** [comment]
This means that location services on your phone can't get a GPS fix. This can happen for various reasons, but is most common indoors. Can you check that you are in an area with good GPS reception? You can check if you get a GPS fix with e.g. [GPS Test](https://play.google.com/store/apps/details?id=com.chartcross.gpstest) from Play Store. If your phone has a setting for location accuracy, try setting it to "High accuracy" instead of "Battery saving".

**Comment by RuralYak** [comment]
True, I just wander how uber, maps works so fast ?

**Comment by bilde2910** [comment]
I currently only use Android's "fine" location provider. That means it will try to rely on GPS only. However, there is also a "coarse" location provider that gets the location from the network instead. I can see if I can implement this as a fallback while the device is waiting for a more accurate GPS fix.

**Comment by RuralYak** [comment]
That would be significant improvement. Can you please consider this as feature request please?

**Comment by bilde2910** [comment]
I will actually consider it a bug, since when I made this feature, I thought just using "fine" was enough. If I understand the docs correctly, "coarse" is able to provide an immediate, albeit less accurate, location. So this was a mistake on my part; I really should be using both. :-)

**Comment by natrius** [comment]
Another suggestion for checking your own GPS-Status: SatStat - its open source and available on f-droid as well.

**Comment by bilde2910** [comment]
I implemented a fix for this in v1.1.1. It may take a couple of days for that version to be available on F-Droid. Hopefully, this fixes the issue for you. If it doesn't work for some reason, please reopen this issue and post any new behavior.
