### ISSUE TITLE
Don't use network after a stay period

### ISSUE THREAD

**Issue by licaon-kter** [bilde2910/Hauk#124]
Didn't know how to describe, so...

1.6 HEAD

I've setup 3s and 5m between updates

Everything is ok on the move, but I might stop in a bus stop or at a stop light, and then Hauk doesn't update....as expected.

But once I move again Hauk gets location from the network (I guess, the status says waiting for GNSS)....100m away.....or 1km away.

My proposition, after a stop period don't use network (or don't use if distance is >min distance set in settings)

Thoughts?

**Comment by bilde2910** [comment]
That's odd, but I can see which programming logic causes this to happen. There's no detectable difference between missing GNSS signal and lack of movement with the current implementation because it delegates the "minimum distance" part to Android itself, causing it to stop receiving updates. I can fix this by redelegating the minimum distance check to my own code instead. That should prevent the coarse location listener from being re-enabled if there's still signal, but no movement.

**Comment by bilde2910** [comment]
Sorry for the delay; I've been very busy with uni lately and haven't had time to work on Hauk.

This should resolve the issue. Instead of delegating the distance check to Android, I now do the distance check myself, keeping the GNSS location listener alive and just not submitting data until the distance is greater than the minimum set. If GNSS signal is lost, it should still fall back to network location.

I still don't know what causes the location updates to stop working even when you start moving again, but hopefully this will fix it.

**Comment by licaon-kter** [comment]
> I still don't know what causes the location updates to stop working even when you start moving again, but hopefully this will fix it.

Not sure it stops, maybe it stalls a bit...

So far I've fixed it by setting a really long timeout for stopped.
