### ISSUE TITLE
random_int() call makes Hauk require PHP 7

### ISSUE THREAD

**Issue by VA1DER** [bilde2910/Hauk#135]
The random_int() call in inc.php seems to be solely responsible for making the Hauk server require PHP 7.  Without it, it works perfectly well on PHP 5.6, and likely earlier.

I was able to work around the requirement for random_int() by using the random_compat library.  You might consider including it with Hauk.  https://github.com/paragonie/random_compat

**Comment by licaon-kter** [comment]
Open a PR then :)

**Comment by bilde2910** [comment]
PHP 5.6 is end-of-life since December 31, 2018 and has not received security patches since that date. Running it in production is a security liability; you should really consider upgrading as soon as possible. Hauk is built to avoid dependencies on other projects and libraries to the greatest extent possible, and I don't really see adding support for an end-of-life version of PHP to be good enough reason to change that. So while I thank you for your suggestion, I'm afraid I will not be implementing this.

Using the function `crypto_rand_secure` from the user notes of `openssl_random_pseudo_bytes` in the PHP documentation would (probably) be a viable replacement for `random_int` on PHP<7 without requiring a library to be added, but then again, I don't see the value of adding this as it would encourage using a dangerous, outdated version of PHP. PHP 7.x is already available for all major server operating systems and distros.

**Comment by VA1DER** [comment]
PHP5 is receiving security updates on Debian until at least next month.  Possibly longer.  That being said, it is of course completely up to you how you want to handle this.

**Comment by bilde2910** [comment]
The latest version of PHP 5 on Debian 8 "Jessie" is 5.6.40, which is also the latest version from [upstream](https://www.php.net/ChangeLog-5.php). PHP 5 is not available in Debian 9 or 10, but Debian 8 is still in LTS, so it *is* indeed receiving updates - but unless Debian themselves are patching issues in PHP, there are no security updates for PHP 5 on Debian despite this. PHP stopped maintaining 5.x as of the same version Debian currently has the 5.x branch at in Jessie, so it doesn't look like anything has happened on the patching front since the upstream EOL. Feel free to correct me if I'm wrong on this.

**Comment by VA1DER** [comment]
It's updated often enough that as I checked the revisions just now I had to update my server, though I admit it's been a few weeks since I checked it.  The current Debian Jessie revision is 5.6.40 deb8u11 dated 25 Apr 2020.  The version on my Debian Jessie server was deb8u10 and dated 26 Mar 2020.
