### ISSUE TITLE
Feature request: Memcached on a Unix port

### ISSUE THREAD

**Issue by RomanJos** [bilde2910/Hauk#15]
Would be cool to set `unix:/run/memcached/socket` instead of `127.0.0.1:port`

**Comment by bilde2910** [comment]
This should be possible to implement. If I can figure out how to add support, I'll try and include it in the next release.

**Comment by RomanJos** [comment]
Awesome :smiley:

**Comment by bilde2910** [comment]
Will keep this open until I manage to implement it, as a note to self :-)

**Comment by bilde2910** [comment]
Turns out this was already supported by accident. You could put a UNIX socket path as the hostname and set port to 0 to use UNIX sockets. Both `memcache` and `memcached` supports this feature, but `memcache` requires "unix://" before the path. In order to have better consistency, this will also be the path you have to use in the config.

So to use UNIX sockets in the upcoming version, set your "memcached_host" to "unix:///path/to/memcached.sock" and "memcached_port" to 0.
