### ISSUE TITLE
bad password on each try

### ISSUE THREAD

**Issue by gustlik** [bilde2910/Hauk#156]
Issue solved. Description is a bit unclear so i misunderstood.

**Comment by okanten** [comment]
Hello, how did you fix this? Having the same issue

**Comment by licaon-kter** [comment]
Try to setup pass again, how did you do it?

**Comment by bilde2910** [comment]
What command did you run to enter your password? Also, how did you enter the resulting hash into the config file?

**Comment by okanten** [comment]
Ran the commands in config-sample.php

`htpasswd -nBC 10 "" | tail -c +2`

pasted the hash to password_hash => '',

also tried with htpasswd, doesn't work either.

however, using the default (empty password) hash works

**Comment by bilde2910** [comment]
Does the empty password still work even after you have changed the hash in the config file?

**Comment by okanten** [comment]
Yes, it does actually. I could've sworn I tried empty password with a new hash and got incorrect password earlier. However, I did just enter a new hash with nano instead of vim so idk if that changed something

memcache and memcached are listed when I run phpinfo() within the same server block as hauk.

**Comment by okanten** [comment]
Looks like the config is ignored.

I've changed public_url as well as link style (for aestethics) and none of them are enabled when I enter a blank password (i get example.com/id)

**Comment by bilde2910** [comment]
That means you're being given defaults. The most likely reason is that you're editing the wrong file, or somehow there is a config file for Hauk that takes precedence. If the config file didn't exist, you'd get another error message, so the file does appear to exist *somewhere*, and it's not being saved properly, or another config is taking precedence.

Hauk reads its config files from here, in the following order of preference:

1. /etc/hauk/config.php
2. /usr/local/etc/hauk/config.php
3. **hauk_install_path**/include/config.php

Which of these paths are you using, and can you ensure that the other paths listed above don't exist?

Can you also verify whether you run Hauk in Docker, or directly on host?

**Comment by okanten** [comment]
Damn, I was editing the one in install_path/include/config.php

I tried running install.sh earlier, so that explains why there exists a /etc/hauk/config.php. However, it seems like the install script isnt asking me if I want to place the config file into /etc/hauk/ (I skimmed the script just now), and when I ran it printed this instead of the path:

> The configuration file can be found at: -e

So I figured the script was botched and did a manual install instead. I also got no prompts at all when I ran the script, just FYI. Not sure why, it might be an error on my end

Thank you very much for troubleshooting for me, I really appreciate the effort and fast response

**Comment by bilde2910** [comment]
No worries! Glad to hear you figured it out. That script error isn't supposed to happen - would you mind sharing which shell you're using to install it (zsh, bash, ash, etc)? I can try to test and see if I can figure out what's wrong. Meanwhile I can also add this to the FAQ, to help whoever else might encounter this issue later. :-)

**Comment by okanten** [comment]
I'm using bash version 5.0.3, however I see that the script includes #!/bin/sh so I dont know if that changes anything?

Ran it as instructed in the README (i.e with sudo)

**Comment by bilde2910** [comment]
Very strange. It does appear to work for me, and bash was the shell I tested on when I wrote it. Maybe it's some kind of underlying distribution thing, or some update that might have broken it, possibly. Which Linux distro are you using? I can try doing an install of the distro in a VM later and see if I can reproduce it.

**Comment by okanten** [comment]
Debian 10, Linux 4.19.0-13-amd64

using sudo might be the issue?

**Comment by bilde2910** [comment]
Hmm, it really shouldn't be an issue. `sudo` is used so that the script can access /etc/hauk as well as /var/www or whichever web directory you're using. I'm pretty busy nowadays, but I'll come back to this and see if I can reproduce the issue later on Debian 10.
