### ISSUE TITLE
add changelog

### ISSUE THREAD

**Issue by leela52452** [bilde2910/Hauk#16]
can you please add changelog.
what is [CHANGELOG](https://en.m.wikipedia.org/wiki/Changelog) ?

**Comment by bilde2910** [comment]
A changelog is available on the [releases page](https://github.com/bilde2910/Hauk/releases).

**Comment by leela52452** [comment]
oh.... it is part of release. hmm...
i was expecting in a separate file, helps me understand the direction and progress of project over a period of time.
something is better than nothing.

**Comment by bilde2910** [comment]
There is also a per-release changelog available in the [fastlane directory](https://github.com/bilde2910/Hauk/tree/master/fastlane/metadata/android/en-US/changelogs), sorted by the current [versionCode](https://github.com/bilde2910/Hauk/blob/master/android/app/build.gradle#L10), for use with the F-Droid store. However, I prefer to have as few places as possible to store the changelog, that's why I recommend the releases page :-)
