### ISSUE TITLE
Feature request: optionally show position of 'viewers' on map

### ISSUE THREAD

**Issue by inos-github** [bilde2910/Hauk#17]
First of all thanks for sharing this great project!

From the 'viewer' point of view it would be nice to see not only the shared location but the own position (if available) as well.

Another idea: is it much work to integrate this into nextcloud as an app?

**Comment by bilde2910** [comment]
Thanks a lot for your feedback!

>From the 'viewer' point of view it would be nice to see not only the shared location but the own position (if available) as well.

This is planned, but I don't know exactly when I can get back to it. I'll leave this issue open until I've managed to implement it.

>Another idea: is it much work to integrate this into nextcloud as an app?

This will not happen, unfortunately. Hauk was made to be independent from other applications; in fact one of the reasons I made this was to get a non-Nextcloud alternative for PhoneTrack. There's not really any obvious purpose that I can see to have this integrated with Nextcloud. That said, go check out PhoneTrack, that might be what you need. :-)

**Comment by RuralYak** [comment]
One good reason to integrate it with some third parties is user authentication. So far you managed to avoid this topic. It is good decision for now. But eventually users and user authentication will show up

**Comment by bilde2910** [comment]
I'll leave that as a future concern for now. Since this project is meant to be self-hosted, chances are there will be very few users using each instance, all of them likely in the admin's circle of friends. At least for now, a static password should be sufficient for that purpose.

However, if there is need for it, instead of going through third party OAuth logins, I could consider adding htaccess-like authentication later. That would necessitate having a "username" field in the app, however. Not sure how I can solve that now, but I can cross that bridge when I come to it if this becomes a wanted feature later.

**Comment by natrius** [comment]
Actually, there are multiple other services to self-host where user-authentification is needed already. I like  Hauk because nothing like that is needed. I can show it to my friends and if they have the app and the password they can use it without creating an extra user.

The "show my own position as viewer" wold be nice but i don't know if that is possible with the browser.

**Comment by inos-github** [comment]
> > Another idea: is it much work to integrate this into nextcloud as an app?
> 
> This will not happen, unfortunately. Hauk was made to be independent from other applications; in fact one of the reasons I made this was to get a non-Nextcloud alternative for PhoneTrack. There's not really any obvious purpose that I can see to have this integrated with Nextcloud. That said, go check out PhoneTrack, that might be what you need. :-)

That's plausible, thanks anyway.


> > From the 'viewer' point of view it would be nice to see not only the shared location but the own position (if available) as well.
> 
> This is planned, but I don't know exactly when I can get back to it. I'll leave this issue open until I've managed to implement it.

What I found so far is [this](https://stackoverflow.com/questions/19335566/get-user-current-location-by-envoking-his-her-phone-inbuilt-geo-location-capabil)


My programming skills are not good enough to write a solution for a PR, unfortunately. Sorry

**Comment by RuralYak** [comment]
Yes, its possible. https://www.w3schools.com/html/html5_geolocation.asp

**Comment by bilde2910** [comment]
This has now been implemented. There is a geolocation control that will display and center the map on the user. The viewer gets a blue marker instead of a red one. Clicking the control again will hide the viewer from the map.

Due to browser security, geolocation of the map viewer only works on HTTPS.

**Comment by inos-github** [comment]
Thank you very much for implementing this feature!!!
Already tested and it's working flawlessly :1st_place_medal:
