### ISSUE TITLE
Feature request: display update lag, time since last location info update received

### ISSUE THREAD

**Issue by RuralYak** [bilde2910/Hauk#20]
Hello,

When connection or client is not stable it is hard to evaluate whether client stays still or just can not reach server. Is it possible to add technical info that will indicate ping or time since last location info updated? Location arrow might become semi-transparent or change its color when data has not been updated for a long time.(e.g. 3-5 times longer than update interval)

Thank you.

**Comment by bilde2910** [comment]
Been playing with this idea for a while and I think I know how I can solve this. Thanks for the suggestion.

Rather than having an N times update interval timeout, I'm thinking a static timeout that can be configured in the config, e.g. 30 seconds without an update by default. This is firstly because timeouts can otherwise vary greatly from client to client, particularly in a group share. (Say the person viewing the map loses connection rather than the people actually sharing; it's better for everyone on the map to visually time out at the same time than have them time out one after each other.) Would this work?

When no data is being received from a client, I will change the arrow/location marker from red to gray, and also switch the speedometer from black to red and have it display "offline" or similar instead of the client's movement speed.

>technical info that will indicate ping

Do you mean ping from map to backend when viewing the map, or from app to backend for the person sharing their location?

**Comment by RuralYak** [comment]
Hi

> Been playing with this idea for a while and I think I know how I can solve this. Thanks for the suggestion.
> 
> Rather than having an N times update interval timeout, I'm thinking a static timeout that can be configured in the config, e.g. 30 seconds without an update by default. This is firstly because timeouts can otherwise vary greatly from client to client, particularly in a group share. (Say the person viewing the map loses connection rather than the people actually sharing; it's better for everyone on the map to visually time out at the same time than have them time out one after each other.) Would this work?

I believe we mix 2 different timeouts here.

Observer(WebBrowser) <--- TimeoutA ---> HaukBackend <---- TimeoutB ---> Android(Hauk client)

For TimeoutA that happens between web browser and backend the most appropriate handling strategy would be visual notification for the whole map that connection been lost. This timeout could be detected by js client that communicates with server.

For TimeoutB handling strategy could be change of the arrow marker appearance to inform other observers about its outage.
 
> Do you mean ping from map to backend when viewing the map, or from app to backend for the person sharing their location?

I meant TimeoutB. But covering TimeoutA also could be a separate feature request.

**Comment by bilde2910** [comment]
Thanks for the clarification. I'll try and see what the best way of solving this would be, and will get started on working on this soon.

**Comment by bilde2910** [comment]
Both TimeoutA and TimeoutB are now implemented.
