### ISSUE TITLE
Clean up intall instructions 

### ISSUE THREAD

**Issue by BrookeDot** [bilde2910/Hauk#21]
Hi there, 

I just upgraded to 1.1 and really like that `frontend` and `backend-php` are now separated out since I customized my frontend UI a bit. However, this is a bit unclear in the README.MD
> Copy everything in the "backend-php" and "frontend" folders in this repository to somewhere in your web root.

Previously I pointed the web root to `/html/backend` and everything worked. Since both `frontend` and `backend-php` are required it seems no longer possible to point to a single folder. I ended up copying everything in `backend-php` and `frontend` to `/app` then pointing my webroot to this folder.  Everything is now working as expected. Is this the intended method? 

I'm happy to submit a PR for documentation improvements once I know how this is suppose to work. 

Perhaps another method would be to have a main `index.php` file that includes the required files, much like an auto-loader? Help figuring out how this is suppose to work would be great.

**Comment by bilde2910** [comment]
Hi,

The change was made to split the static frontend code away from the PHP backend as part of an upcoming merge of PR #10 that will introduce an alternate non-PHP backend to the project. This was done so that the browser frontend and assets aren't duplicated between them. The correct manual installation procedure now is to do as you did; copying the contents of `backend-php` and `frontend` into the same folder and using that as the web root. Though I guess the installation procedure isn't totally clear on that matter.

I could write a simple `install.sh` script that does the work of copying everything correctly to a specific web root directory, e.g. `./install.sh /var/www/html`. This could then be the preferred way to do a non-Docker install. An improved version of the current installation procedure could then be included as a means to do a fully manual install without having to run a script.

If you have suggestions for improvements, that'd be much appreciated :-)

**Comment by BrookeDot** [comment]
That makes sense, for now, I submitted https://github.com/bilde2910/Hauk/pull/23 which I hope makes things a bit clearer. These will need to be adjusted with Ruby is an option.

**Comment by bilde2910** [comment]
Thanks for the contribution. I've merged #23 and will update the README once the Ruby backend is an option, and when an install.sh script is in place.

Issue closed: Fixed by author in #23.
