### ISSUE TITLE
Shared position constantly visible

### ISSUE THREAD

**Issue by natrius** [bilde2910/Hauk#25]
A user shared his position and told me he was not able to end it manually in the app directly. He told me he could find options in the dropdown menu to end sharing, that was yesterday. 
Unfortunately the last position is still visible via the link with the last known speed. 

Is there a way to read what server version is right now "installed" and if i should have upgraded it? I will try to reproduce it myself and will give more info. 

If you tell me where i can send you the link and what more information do you need, i will get you as much information as possible.

**Comment by bilde2910** [comment]
If I understood the issue correctly, this should be fixed by the resolution of #28. If the app crashes or closes unexpectedly, reopening the app will prompt the user to resume the share. If the user **chooses to resume the share**, they can then click on the "stop sharing" button that appears, which will send the stop message to the server and clear stored location data.

If the user chooses to not resume the share, location data will still be stored on the server until its initial expiration time. I.e. the share has to be resumed in order for the user to be able to gracefully stop it.

Network connectivity is still required in this case for a graceful shutdown.

**Comment by natrius** [comment]
`curl -o /dev/null -D - https://YOUR_HAUK_URL/api/create.php 2>/dev/null`

Can you please write that in the readme as well? I was just trying to search if my update was succesfully :p

**Comment by bilde2910** [comment]
> Can you please write that in the readme as well? I was just trying to search if my update was succesfully :p

Sure thing. Added it to the [FAQ](https://github.com/bilde2910/Hauk/wiki/FAQ#how-can-i-check-which-version-of-hauk-i-am-running).
