### ISSUE TITLE
Connection error with User CA

### ISSUE THREAD

**Issue by murizorun** [bilde2910/Hauk#26]
Hello,

On the android client I get a Connection error: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

The endpoint I try to connect is configured on https with a certificate singed by my own CA.

The CA is installed and trusted on my android 9 phone and is available under Settings > ... > Trusted credentials > User and other apps that connect to similar endpoints work.

I've checked a bit the android documentation and it seems since Android 7 behavior for user trusted CA changed a bit.

https://android-developers.googleblog.com/2016/07/changes-to-trusted-certificate.html

Apps now have to specify in the manifest file if they trust user CAs...

https://developer.android.com/training/articles/security-config

https://developer.android.com/training/articles/security-config#certificates

I could try to make a change and pull request if you want to make this change ;).

Thanks!

**Comment by murizorun** [comment]
There is an already implemented solution over at siacs/Conversations here on github.

The android manifest file contains reference to this networkSecurityConfig file:

[AndroidManifest.xml](https://github.com/siacs/Conversations/blob/master/src/main/AndroidManifest.xml#L57)
     
```xml
 <application
         ...
         android:networkSecurityConfig="@xml/network_security_configuration"
         ...>
```

And the file closeby: [network_security_configuration.xml](https://github.com/siacs/Conversations/blob/master/src/main/res/xml/network_security_configuration.xml)

```xml
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <base-config>
        <trust-anchors>
            <certificates src="system" />
            <certificates src="user" />
        </trust-anchors>
    </base-config>
</network-security-config>
```

**Comment by bilde2910** [comment]
Hi, and thanks for your suggestion!

I will need a very convincing reason for allowing user CAs. The person you share the location with will get a security error when they try to view the link unless they also have the same root CA installed, and if they dismiss the error to view the map, the security benefits of HTTPS are gone; plain-text HTTP would be just as secure at that point.

Is there any particular reason you cannot use e.g. Let's Encrypt?

**Comment by murizorun** [comment]
Hello,

honestly, I don't really have a strong reason to give you to allow user CAs, ranther than to provide choice for the user.

I've always prefered to generate my own certificates for the services I host for my private group users and this seems to work so far.

While Let's Ecrypt is good for hosting a public facing services, for private groups it just adds another agent that needs to run in you infrastructure and route access to it every 3 months or leave an extra redirect rule on.

Also I see no harm in this project trusting the CAs that the users has added, as the code itself only comunicates with the host the user configures as server endpoint. 

Even if somehow a malicious CA is added there that signs all sorts of bad certificates, it would need quite an elaborate attack to compromise the user location to a different server. Would probably mean an attacker already has access to the location or other processes of the phone.

Also, what server still serves content over HTTP and not redirect to HTTPS? :D

**Comment by bilde2910** [comment]
>While Let's Ecrypt is good for hosting a public facing services, for private groups it just adds another agent that needs to run in you infrastructure and route access to it every 3 months or leave an extra redirect rule on.

I presume this means you're blocking Let's Encrypt by default somehow. Some questions to consider: Do you enforce an IP whitelist, or do you have to be on a specific network to access your instance? Hauk is only really meaningfully used when sharing from a mobile network, which can have a large range of addresses. Do you whitelist the entire mobile network, or do you connect via a VPN? If the latter, the VPN already provides encryption.

You can also request certificates from Let's Encrypt without having to allow them to connect to your server, and this can also be automated. See e.g. [this quick example](https://bjornjohansen.no/wildcard-certificate-letsencrypt-cloudflare) on how to get a wildcard certificate for a domain using CloudFlare nameservers, that automatically renews with no need for interaction. I use this; I set it up once for my domain and it just works automatically in the background. The setup process itself was very quick and easy to follow.

>Even if somehow a malicious CA is added there that signs all sorts of bad certificates, it would need quite an elaborate attack to compromise the user location to a different server. Would probably mean an attacker already has access to the location or other processes of the phone.

If you don't secure the CA well, and the CA private key is leaked, it can be used to create valid certificates for every site on the internet. That's really the main security risk of trusting a custom root CA.

Does everyone in your user group have this root CA installed? They would need to if they're to not get security warnings when viewing the map in the browser.

>Also I see no harm in this project trusting the CAs that the users has added, as the code itself only communicates with the host the user configures as server endpoint.

This is a fair point. I suppose I can allow user-provided CAs, as location data is hardly the most sensitive data, and it is only shared temporarily. And this is a self-hosted solution after all. But in the vast majority of cases where people think they need this, the problem is much better solved using a trusted CA-signed certificate from Let's Encrypt. The only case where a custom root CA is really the only option is if you are intentionally running an sslstrip MITM on your network. That's really why I've been reluctant in adding this. I can see if I can add this to the next update, but the risk of using a custom CA is entirely on you.

**Comment by RuralYak** [comment]
Yes, when you use your own CA the risk is on you and, usually, other projects directly have a checkbox for it. Like "trust user certificates". So I would vote for having a choice since lets encrypt is good but not an ideal solution

**Comment by bilde2910** [comment]
This will be live in v1.1.1. It may take a couple of days for the app to be available on F-Droid. An FAQ entry will be made regarding usage of user-provided CAs.

**Comment by murizorun** [comment]
Thank you for considering and implementing this!
