### ISSUE TITLE
Android enhancement request: Show Hauk when notification message clicked

### ISSUE THREAD

**Issue by RuralYak** [bilde2910/Hauk#27]
Hello,

When notification shown and you click on it nothing happens. Is it possible to add reaction to click to show Hauk when pressed?

![ss1](https://user-images.githubusercontent.com/25221496/64892090-600cd380-d628-11e9-9fd7-bc62f9fc5a4b.jpg)

Thank you.

**Comment by bilde2910** [comment]
I considered this and did actually try to implement it, but when the notification was clicked, I ended up spawning a new instance of the app instead (i.e. looked like it wasn't sharing, like the app was just restarted, so you can't interact with the share anymore).

I'll keep playing around with it and see if I can figure it out. That said, if anyone happens to know of a way to return the app to an already existing, running activity when notification is clicked, I'd love to hear about it. Asking Android to spawn an activity makes it create an entirely new instance instead of resuming the old one. If I can't figure it out, I'll have to put this on hold for a while. It's a low priority issue for now.

**Comment by bilde2910** [comment]
I actually managed to implement this thanks to an old newsgroup thread I stumbled upon that had the correct settings for me to use. I guess I can blame myself for not looking into the documentation well enough - but in my defense, the Android developer documentation covers a *lot* of topics, so it can be hard to find that needle in the haystack.

This will be live in v1.1.2.

**Comment by RuralYak** [comment]
BTW, F-droid still on 1.1

**Comment by bilde2910** [comment]
> BTW, F-droid still on 1.1

Oh, that's actually a bit curious. F-Droid has its own build process; I unfortunately don't have control over it. Normally it would only take a couple of days, but maybe it's delayed for some reason. I assume it'll be built within a few more days.

**Comment by RuralYak** [comment]
Did send you a personal message to your post inbox. Let me know if it works for you or not

**Comment by bilde2910** [comment]
> Did send you a personal message to your post inbox. Let me know if it works for you or not

Received your mail regarding the Xiaomi issue; replied

**Comment by bilde2910** [comment]
The v1.2 update that has this feature has now been scheduled for release. v1.2 is tagged, but it might take anywhere from a few days to a week before the update shows up on F-Droid.
