### ISSUE TITLE
Feature request: multiple sessions

### ISSUE THREAD

**Issue by RuralYak** [bilde2910/Hauk#30]
Hello, 

I would like to propose to discuss a possibility of having multiple running sharing sessions with ability to add, stop/start and kill them.

user story behind that is simple: sometimes you want to share your location for a longer period of time (e.g for family) but same time want to share location to acquaintances for a short time.

Thanx.

**Comment by bilde2910** [comment]
That sounds like a good idea. However, it will be a lot of work to implement, so if I get around to this, it will be part of a bigger release. I'll also need to figure out a good way to solve this UI/UX-wise.

**Comment by bilde2910** [comment]
The way this will be implemented is:

- When you create (or join) a share, instead of having a "share tracking link" button, you instead have a list of URLs that you are currently sharing your location to.
- When you start/join a share, the link for that share is added to said list.
- Each link in the list has separate "stop" and "share" buttons next to them.
- There will be a button "create new tracking link" that creates a new single-user share link. This link will then appear in the list of links in addition to the one(s) already there.
- You can add as many additional links as you want to the list. You can then make a new link for every person you wish to share to, for example.
- Tapping the "stop" button for one link in the list will invalidate it and send "share expired" to viewers of that particular link, but will not affect the other active links.
- Stopping the share with the main stop button will stop sharing to all links.
- Group shares you are adopted into will display in the link list. Stopping one of these will remove you from that group, but others still in the group can still exchange their own locations with each other.

**Comment by bilde2910** [comment]
This will be live in v1.2.

**Comment by bilde2910** [comment]
v1.2 has been tagged and should be up on F-Droid within anywhere from a few days to a week.
