### ISSUE TITLE
Feature request: Add broadcast intents

### ISSUE THREAD

**Issue by jvandenbroek** [bilde2910/Hauk#37]
Would be great if we could use broadcast intents to start/stop sharing and launch the share link action. This way it can be easily automated with an app like (but not limited to) Tasker. Maybe an extra single intent could be added to start sharing and share tracking link if succeeded. The extra "connection established" confirmation dialog could be suppressed in that case.

**Comment by bilde2910** [comment]
I'll look into making this possible, but there will have to be a setting to turn this on and off (with off being the default), or a first-use approval request for each app that uses this broadcast intent, because of privacy implications of having apps automatically start sharing. I've already purchased Tasker, so I can definitely do some testing with this and see if I can find a good solution. Thanks for the suggestion.

**Comment by bilde2910** [comment]
This will be live in v1.3. Documentation will be updated accordingly. I will post a link here with usage instructions once the documentation is finalized.

**Comment by jvandenbroek** [comment]
Couldn't wait and built it myself, it works great, thanks! Neat implementation to ask for permission on first request :)

**Comment by tyler71** [comment]
Works in Macrodroid as well
[![macrodroid sent intent example](https://i.imgur.com/N8T6CyP.jpg)](https://i.imgur.com/IBUKbN5.jpg)
