### ISSUE TITLE
iPhone (iOS?) app planned?

### ISSUE THREAD

**Issue by natrius** [bilde2910/Hauk#43]
Hello, 

do you plan an ios version for the app? Got this asked today :)

Greetings

**Comment by bilde2910** [comment]
Unfortunately at this point an iOS app is not planned. This is because iOS app development requires the usage of a Mac for development and deployment, and comes with a $99/yr fee for submission of apps to the App Store. I do not have access to a Mac, and currently I am not in a position to pay the membership fees to join the Apple Developer Program even if I did have one. So unless someone else volunteers to port the Android app to iOS, and maintain it, unfortunately this cannot be done. Sorry.

**Comment by sdstolworthy** [comment]
I'd be interested in working on this port

**Comment by sdstolworthy** [comment]
Is there anyone else that would want to work on this with me?

**Comment by licaon-kter** [comment]
@sdstolworthy Just start working and maybe others will join you, leave a link here. :)

**Comment by bilde2910** [comment]
The main problem right now is funding to get on the App Store. I would need to pay a $99/yr subscription to Apple to have a developer profile there. The only alternatives for me to really make that happen would be either crowdfunding that sum on e.g. Patreon, or charging for the app to offset the cost. I'm not an Apple user, and I'm on a student budget, so I can't easily pay it out of pocket especially since I wouldn't get any direct benefit from it myself.

I have an access to an old iPhone 5 I can use for testing, for what it's worth, so getting a live device to work on shouldn't be an issue.

If you wish to help out with making it, I'd be more than happy to help explain the protocol for establishing sessions, pushing updates etc. Though if you actually do plan to do this, I'd appreciate just a heads up before you start :-)

**Comment by tuffnerdstuff** [comment]
I totally understand the standpoint of @bilde2910. As a developer I'm totally put off by Apples way of making money off developers instead of providing all development resources for free. That said maybe using OwnTracks in tandem with [hauk-snitch](https://github.com/tuffnerdstuff/hauk-snitch) (my humble project) might be a workaround for you iPhone users, as OwnTracks provides an iPhone App. It requires some additional set-up and its utility depends on your use-case.

**Comment by Anoerak** [comment]
Hi,

what about a web App?

**Comment by EinfachRuwen** [comment]
I thought anyone wanted to code an Hauk app? 😭
I am right now thinking about doing so, because I can't find any good alternative to share my location on iOS - privacy friendly.
For my Android fellas, I have my own Hauk instance, but it's too bad, that there is no iOS-App.
Any developer still developing anything or is anyone interested in coding a Hauk app for iOS?

**Comment by NickBouwhuis** [comment]
I did some work on an iOS app

https://github.com/NickBouwhuis/hauk-ios

Base functionality is there, but needs some work.

Can't publish in App Store or TestFlight because I don't have a paid developer account yet.

Edit: here is the testflight link: 

https://testflight.apple.com/join/1VUJFz4Q

**Comment by harryd337** [comment]
@NickBouwhuis this is great! If you set up a Patreon to fund the developer account I'm sure enough people would contribute to cover it

**Comment by NickBouwhuis** [comment]
> [@NickBouwhuis](https://github.com/NickBouwhuis) this is great! If you set up a Patreon to fund the developer account I'm sure enough people would contribute to cover it

I have added sponsorship options to the repo <3
