### ISSUE TITLE
[language] german

### ISSUE THREAD

**Issue by natrius** [bilde2910/Hauk#44]
Please set up german for translating :)

Greetings

**Comment by bilde2910** [comment]
I think I managed to set up Weblate so that new languages are accepted automatically. Head over to [the translator portal](https://traduki.varden.info/projects/hauk/), log in, then you can go into each component listed and click "Start new translation". That should bring up a menu where you can pick German. (I should probably update the README, didn't get around to that yet.) Thanks for willing to translate :-)

**Comment by natrius** [comment]
Should be done, hopefully mostly correct :D

**Comment by hurradiegams** [comment]
maybe someone else germanspeaking should have a look at our translations, just for good measure

**Comment by bilde2910** [comment]
Thank you so much for helping out with the translation! I really appreciate your contributions, and I'll make sure you are both credited in the README :-)

Do you wish to translate the backend and frontend as well before I push out the v1.3 update? They're each around 80-90 words or 10% of the total word count. (The Android client is 718 words or about 80%.)

**Comment by natrius** [comment]
Sure, why not :)

**Comment by natrius** [comment]
Should be finished, had some spare time :p

**Comment by bilde2910** [comment]
Thank you!
