### ISSUE TITLE
feature request: named location share links

### ISSUE THREAD

**Issue by aslmx** [bilde2910/Hauk#56]
Hi,

just found Hauk yesterday after looking for a possibility to let others know when exactly i will be at a meeting point during high traffic times and not having to give a new ETA via XMPP every 5 minutes while driving.
Excellent Job, i really like it!

One Feature Request though: it would be really nice to have a possibility to share your position to a constant link, or somehow to a pre-shared one.
This way one could share the link with others, let them even bookmark it and then just start "broadcasting" your location to that link whenever necessary.
No need to send a new link.

Also if these links could be named like with your name or so, that would even be better!

Is that somehow possible or even planned already maybe? :-)
I'd really appreciate it! Thanks!

**Comment by bilde2910** [comment]
I honestly hadn't considered this, but it's worth looking into. I could make it possible for the client to request a specific URL rather than getting assigned a random one from the server, and if it's free to use, that will be the chosen one.

When #54 is implemented, I could also implement a user whitelist for specific URLs, so only some users are allowed to request certain URLs (to prevent them being inadvertently used by others). I'll take a look at it and see what I can come up with. I'm pretty busy with other things right now though, so I might not be able to look into this right away.

**Comment by tyler71** [comment]
Would it be possible to add this onto sending a intent? Such as specifying a extra like `url` 
If that's enabled, it may not need to initiate a share UI prompt since it would already be known

**Comment by bilde2910** [comment]
Sure. There is already Tasker integration, so I can add another one that doesn't prompt the "Share via" dialog. I don't know how to return the success/failure status in that case though.

**Comment by bilde2910** [comment]
This will be live in v1.4. I realized still need to add the silent Tasker integration. I will reopen until I've managed to add it.

**Comment by bilde2910** [comment]
This is now live and is being pushed out to stores. Documentation on the new Tasker hook is available [on the wiki](https://github.com/bilde2910/Hauk/wiki/Tasker-integration#start-a-single-user-share-then-display-the-link-on-screen).

**Comment by aslmx** [comment]
Naming the location share works for me as i requested. Thanks!
