### ISSUE TITLE
Some enhancements that came up in my mind

### ISSUE THREAD

**Issue by RomanJos** [bilde2910/Hauk#6]
I make a tour of the town with Hauk and some enhancements came up to my mind : 

- My phone kill the app to save the batterie, on the map its not showing that i'm not connected anymore it would be nice to have a timeout on the server side 
- When i'm not moving the arrow start doing some 360° freestyle, maybe you can attach it to the gyroscope of the phone ?
- Is there any satellite maps except the one of google ? so we can choose on the live maps which one we want
And for the last its maybe a little overkill
- Can you add a list of public server that the phone can ping to see if they are up so any users can share their position without setup a server ? I would love to share mine !
Thanks for your work and your fast support :smile:

**Comment by bilde2910** [comment]
Thanks for your requests!

>My phone kill the app to save the batterie, on the map its not showing that i'm not connected anymore it would be nice to have a timeout on the server side

What phone do you have? Android may kill apps that are in the background if it needs resources, but normally killing a foreground service (like Hauk) should only happen if the resource pool is completely exhausted. Any idea if the similar app Glympse is also affected by this behavior?

Some manufacturers also like to put additional restrictions in place. OnePlus, for example, has its own "battery optimizations" section in device settings that you may have to manually whitelist the app in for it to work.

I don't have a timeout currently because there are legitimate reasons for the app to fail sending updates to the server, like if the phone moves out of cell service. I can see if I can add a feature to the client that shows a small notice when no updates have been received for the past X minutes (1 minute, 2 minutes, whatever works best).

>When i'm not moving the arrow start doing some 360° freestyle, maybe you can attach it to the gyroscope of the phone ?

The phone gyroscope can be notoriously unreliable. I can certainly add this and test it, though.

>Is there any satellite maps except the one of google ? so we can choose on the live maps which one we want

Yes, the map can use any provider that can be supported by Leaflet. Take a look at the [Leaflet provider demo here](https://leaflet-extras.github.io/leaflet-providers/preview/), in particular the `Esri.WorldImagery` provider. I don't know what requirements Esri has, or if you have to subscribe to their service to be allowed to use their maps. Mapbox also offers satellite maps IIRC, I'm pretty sure these can also be used by Leaflet. You have to sign up for an account and get an API key to use it, but their free tier has a pretty generous quota.

>Can you add a list of public server that the phone can ping to see if they are up so any users can share their position without setup a server ? I would love to share mine !

This is not really desirable right now, particularly from a privacy perspective. The issue is that if you connect the Hauk app to a third party server, you have to trust the administrator of that server that they don't log the data. There is nothing actually stopping a server owner from stalking you and otherwise using your location data maliciously if you send it to them. This is actually a generalized problem with self-hosted software - if anyone can host an instance, and you don't know who the host is, how can you hold them accountable? So you are strongly recommended to host your own instance.

Users unwilling to host their own instances will be left without any assurances of the privacy of their data, so they'd be actually better off using public services like Glympse, which at least have privacy policies to adhere to.

Thanks for your feedback, I appreciate it :-)

**Comment by RomanJos** [comment]
Hi this issue is for my phone only, Its even killing the sms app if I don't disable it lol I tested Glypse and yeah after 1-2 minutes the website didn't have any update of my phone.

> I can add a feature to the client that shows a small notice when no updates have been received for the past X minutes (1 minute, 2 minutes, whatever works best).
Yeah you can maybe write a warning on the server side that show after 1 or 2 minutes there has been no update and after the time sharing duration that the client selected  before sharing the position the link would be either on a expired state or on a "archive" state where the last position is grayed for example

> Users unwilling to host their own instances will be left without any assurances of the privacy of their data, so they'd be actually better off using public services like Glympse, which at least have privacy policies to adhere to.
Yeah you right on that point
Can't wait to see this app grow up !

**Comment by dror3go** [comment]
> When i'm not moving the arrow start doing some 360° freestyle, maybe you can attach it to the gyroscope of the phone ?

I don't like the idea of using the gyroscope for that. @bilde2910 How about changing the icon from an arrow to a circle?

**Comment by bilde2910** [comment]
>How about changing the icon from an arrow to a circle?

That's actually a really good idea! I can change it to a circle if the speed is 0 km/h. Thanks for the suggestion :-)

**Comment by bilde2910** [comment]
The icon will now be a circle when the velocity is "0.0" of whichever unit of measurement is configured.
