### ISSUE TITLE
A bunch of features

### ISSUE THREAD

**Issue by plague-doctor** [bilde2910/Hauk#63]
Thanks for your brilliant app. Here it is a bunch of suggestions to make your solution perfect and  complete for me, my family and my friends.

### Back-end
- multiple users;
- users authentication;
- allow to store multiple tracks (maps of trips, escapades, holidays) and present them on a map;
- allow to select above tracks by a meta (date, country, tags, etc) defined by a user;
- export tracks to gpx;
- import tracks from gpx.

### Front-end (mobile app)
- ability to collect GPS positions without instant synchronization. In case there is no connection, or one doesn't want to use a data on roaming;
- ability to upload collected data in bulk at convenient time (WiFi available);
- ability to attach a metadata (tags, etc) to collected data.

I hope this make sense.

P.S. [bfabiszewski](https://github.com/bfabiszewski/ulogger-server) has created a skeleton for such functionality, but his approach lacks encryption and all privacy bells-and-whistles which your solution has got.

**Comment by bilde2910** [comment]
Thanks for your requests!

>* multiple users;
>* users authentication;

Already available since v1.4 (#54). User authentication is enabled when [auth_method](https://github.com/bilde2910/Hauk/blob/master/backend-php/include/config-sample.php#L55-L66) is set to `HTPASSWD` and a corresponding [htpasswd file](https://github.com/bilde2910/Hauk/blob/master/backend-php/include/config-sample.php#L87-L96) exists with the users in it (created as described in the sample config file).

>* allow to store multiple tracks (maps of trips, escapades, holidays) and present them on a map;
>* allow to select above tracks by a meta (date, country, tags, etc) defined by a user;
>* export tracks to gpx;
>* import tracks from gpx.

This is currently out of scope for Hauk. Hauk is meant only for temporary location sharing, akin to Glympse. For your use case, have you considered OwnTracks or maybe PhoneTrack? I think both of them are more geared towards permanent storage and allow exports.

>* ability to collect GPS positions without instant synchronization. In case there is no connection, or one doesn't want to use a data on roaming;
>* ability to upload collected data in bulk at convenient time (WiFi available);
>* ability to attach a metadata (tags, etc) to collected data.

I feel like this is also not really in scope for the same reason, since the location data is supposed to be "hot" - old data is discarded by the server anyway.
