### ISSUE TITLE
Increase the link entropy

### ISSUE THREAD

**Issue by licaon-kter** [bilde2910/Hauk#73]
...by using longer strings.

Yes, 8 chars can be remembered, but is anyone using them like that and not share them via some encrypted SMS, XMPP or Matrix? 

Also, case sensitive? Why bother?

I'd rather see this bumped to 32 chars or more.

**Comment by bilde2910** [comment]
I explained this in more detail in #55:

>As for the length of the ID in the URL - eight characters offers 36<sup>8</sup> unique combinations - that is 2.8 trillion different combinations (2.8 × 10<sup>12</sup>) of URLs. It shouldn't be possible to feasibly brute force that big of a key space. If you were able to try 1000 different URLs every second, it would take around 45 years on average to discover your URL (assuming you are sharing your location 24/7 for that long).

For reference, Glympse currently uses either 6 or 8 characters for their public service. A significant advantage of short links is that they can still be typed (e.g. you receive the link as a text on your phone, and have to type it in on your computer to get it up on a bigger screen). I also don't really see the real advantage of using longer links since the chance of stumbling upon a link by accident that happens to be active at that time is so astronomically small.

As said in that other issue as well, I'd be happy to accomodate, but currently I fail to see the real advantage.

>Also, case sensitive? Why bother?

You're right that I probably should change this.

**Comment by licaon-kter** [comment]
Right, I guess my bandwidth would be an issue, also the link is usually short lived.

You could case sensitiveness and add lowercase alphabet too, making it a bit better. :)

**Comment by bilde2910** [comment]
I could add several different presets to choose from, e.g. 4+4 uppercase/numeric, lowercase/numeric, mixed case/numeric, UUID, random chars, etc. That should add different options so you can pick and choose what works best.

**Comment by bilde2910** [comment]
Added. Next build on Docker should be live in half an hour or so.

**Comment by licaon-kter** [comment]
Thanks for the quicks fixes.

Sorry for spamming you with issues/requests :-D

**Comment by bilde2910** [comment]
No worries! I appreciate the feedback, even if it will take some time to deal with it all :-)
