### ISSUE TITLE
Detect BACK button/gesture

### ISSUE THREAD

**Issue by licaon-kter** [bilde2910/Hauk#77]
...so the app doesn't stop sharing.

Eg. Maybe pop-up a dialogue with "are you sure you want to stop?" or have a Setting to either ignore BACK (minimize) or stop sharing and exit.

**Comment by bilde2910** [comment]
Wait, it actually stops the share? I'll admit I never actually tested that. It should not be that way and I'll definitely fix that Would probably have to put the specific behavior setting in the settings menu once #74 is done.

**Comment by licaon-kter** [comment]
Yes, it might be ROM specific, more aggressive ones might choose to kill the app instead (in the name of battery savings).

**Comment by bilde2910** [comment]
The issue here was that clicking the back button would kill the Hauk UI but leave the session running in the background. When reopening the app, the UI would see that there was a share cached, but didn't see that the service was already running. It would then start a new session on top of the old one; the old one still pushed location which somehow caused the new one to not get a location fix. The patch makes the UI look for an existing running session instead and if it finds one, will silently stop the old session and resume the shares in a new session.
