### ISSUE TITLE
Allow more input editing for NEW tracking link

### ISSUE THREAD

**Issue by licaon-kter** [bilde2910/Hauk#79]
...as right now one can only modify group or not, while I might want a different e2e pass or share duration or update interval.

Can the app and/or server handle multiple different update intervals?

**Comment by bilde2910** [comment]
This is actually very tricky to change. A lot of the logic in the app relies on there only being a single session active at a time. The E2E password, interval and duration are all linked to the underlying session rather than each share link on the backend. Changing these parameters therefore requires creating a new session.

A very significant amount of code would have to be rewritten to make it possible to have multiple sessions active at a time, which makes me reluctant to implement this feature. I'm not really decided on it yet

**Comment by bilde2910** [comment]
I think I'll settle on this being `wontfix` for now. The amount of changes needed in the app to add multiple sessions is too significant to warrant such a relatively minor feature at this point. Thanks for the suggestion, however!

**Comment by licaon-kter** [comment]
I often end up with links created with a previous used update interval that might not be good for this new situation, either too rare or too often.

I'm forced to live with it since stopping the link and having everyone else use the new one is cumbersome. :(
