### ISSUE TITLE
Split OFFLINE status

### ISSUE THREAD

**Issue by licaon-kter** [bilde2910/Hauk#81]
...in either NO LOCATION and OFFLINE (no connection from the app)

What I didn't check, does the app stop reporting if there's no GPS lock? Maybe it could report online+nolock too, less often though.

**Comment by bilde2910** [comment]
>does the app stop reporting if there's no GPS lock?

Yes. The location updates from the app are triggered by Android itself when a GNSS update is received by the geolocation sensors; when a fix can't be obtained, Android simply stops triggering the Hauk location updates, which is responsible for sending messages to the backend. I think maybe a better option would be to relabel the "offline" status into "location unknown" or some shorter variation instead. "Offline" strictly means that the client does not have connectivity, while "location unknown" just means that the backend hasn't received a location update in a while, which could be either because it's actually offline, or because the client itself doesn't know where it is.

**Comment by licaon-kter** [comment]
Actually this is sort of a duplicate of https://github.com/bilde2910/Hauk/issues/76
