### ISSUE TITLE
Site timer and app timer might go out of sync

### ISSUE THREAD

**Issue by licaon-kter** [bilde2910/Hauk#86]
Server/app HEAD

Share, open browser, gps lock, see "2min ago", put device offline, see "10min ago", put device online, some time pass, browser says EXPIRED on top...looking at the device...still 1min 22sec to go

**Comment by licaon-kter** [comment]
As seen here I guess not an actual Hauk issue per se: https://github.com/bilde2910/Hauk/issues/76#issuecomment-563324983

Not sure these can be synced better.

**Comment by bilde2910** [comment]
It's hard to properly verify if the devices are actually synced. Does it still happen with them in sync?

**Comment by licaon-kter** [comment]
Looks better when (almost) in sync, yes.

**Comment by bilde2910** [comment]
This issue actually appears to be caused by a server/browser de-sync rather than [the other issue](https://github.com/bilde2910/Hauk/issues/76#issuecomment-563324983) which is an app/browser de-sync problem. I can possibly fix this by having the backend tell the browser what time it actually is, and then letting the browser adjust its perception of time based on that, taking the offset into account.

**Comment by bilde2910** [comment]
Time traveling only causes problems, so the browser will now reject its own understanding of time and trust the server instead.
